/**
 * Maps actor names to their incoming and outgoing message types.
 *
 * Extend this interface through module augmentation when you want typed actor
 * messages without generating types with the CLI. For each actor, `toServer`
 * defines incoming messages that a client sends to the actor. `toClient` defines
 * outgoing messages that the actor sends to connected clients.
 *
 * @example
 * ```typescript
 * declare module "@base44/sdk" {
 *   interface ActorRegistry {
 *     ChatRoom: {
 *       toClient: { type: "joined" | "left" | "message"; userId?: string; from?: string; text?: string };
 *       toServer: { type: "message"; text: string };
 *     };
 *   }
 * }
 * ```
 */
export interface ActorRegistry {}

/**
 * Lists actor names when your project includes types generated by the CLI.
 *
 * The generated names provide autocomplete for deployed actors. To define
 * incoming and outgoing message types manually, augment {@link ActorRegistry}.
 */
export interface ActorNameRegistry {}

type AllActorNames = keyof ActorRegistry | keyof ActorNameRegistry;

type ToClientFor<N extends string> = N extends keyof ActorRegistry
  ? ActorRegistry[N] extends { toClient: infer I }
    ? I
    : unknown
  : unknown;

type ToServerFor<N extends string> = N extends keyof ActorRegistry
  ? ActorRegistry[N] extends { toServer: infer O }
    ? O
    : unknown
  : unknown;

/**
 * Options for {@link ActorRef.connect}.
 */
export interface ActorConnectOptions {
  /**
   * Connection ID that the actor receives as `conn.id`.
   *
   * Specify a stable value, such as a value persisted per client, so
   * reconnections from that client reuse the same connection ID. Omit this property
   * to generate an ID.
   */
  id?: string;
}

/**
 * Represents an outgoing-message listener registered with
 * {@link Connection.subscribe}.
 */
export interface ActorSubscription {
  /**
   * Removes this listener. Other listeners and the socket stay open.
   *
   * @example
   * ```typescript
   * const sub = conn.subscribe((msg) => console.log(msg));
   * sub.unsubscribe();
   * ```
   */
  unsubscribe(): void;
}

/**
 * Represents a client's WebSocket connection to an actor session.
 *
 * {@link ActorRef.connect} returns this object while the socket connects.
 * The socket buffers messages sent during connection setup until it opens.
 */
export interface Connection<N extends string = string> {
  /** Connection ID that the actor receives as `conn.id`. */
  readonly id: string;

  /**
   * Registers a listener for outgoing messages from the actor.
   *
   * You can register multiple listeners on the same connection.
   *
   * @param callback - Called with each outgoing message sent to this connection.
   * @returns A handle you can use to remove this listener without closing the socket.
   *
   * @example
   * ```typescript
   * const conn = base44.actors.Chat("session-1").connect();
   * const sub = conn.subscribe((msg) => {
   *   if (msg.type === "message") console.log(msg.text);
   * });
   * ```
   */
  subscribe(callback: (data: ToClientFor<N>) => void): ActorSubscription;

  /**
   * Sends an incoming message to the actor.
   *
   * The socket buffers messages until it opens. After {@link close}, the socket
   * drops further sends.
   *
   * @param data - Incoming message to send. Typed through {@link ActorRegistry} when configured.
   *
   * @example
   * ```typescript
   * conn.send({ type: "message", text: "Hello" });
   * ```
   */
  send(data: ToServerFor<N>): void;

  /**
   * Closes the connection and removes all listeners.
   *
   * Safe to call more than once. A connection also closes itself when it fails
   * permanently. See {@link ActorRef.connect} for how to open a fresh connection.
   *
   * @example
   * ```typescript
   * conn.close();
   * ```
   */
  close(): void;
}

/**
 * Represents an actor session selected by actor name and session ID.
 *
 * Call {@link connect} to open the WebSocket and get a {@link Connection}.
 */
export interface ActorRef<N extends string = string> {
  /**
   * Creates or returns the {@link Connection} for this session.
   *
   * Repeated calls return the same connection until it closes. After a permanent
   * failure, such as a missing actor or denied connection, fix the cause and call
   * `connect()` again. Add subscriptions to the new connection.
   *
   * @param options - Optional connection settings, such as a stable connection ID.
   * @returns The {@link Connection} for this actor session.
   *
   * @example
   * ```typescript
   * const conn = base44.actors.Chat("session-1").connect({ id: "tab-abc" });
   * conn.subscribe((msg) => console.log(msg));
   * ```
   */
  connect(options?: ActorConnectOptions): Connection<N>;
}

/**
 * Selects a session for a named actor.
 *
 * Typed automatically when the actor is registered in {@link ActorRegistry} or
 * {@link ActorNameRegistry}.
 */
export interface ActorClient<N extends string = string> {
  /**
   * Gets a reference to an actor session.
   *
   * Clients that specify the same actor name and session ID join the same session.
   *
   * @param instanceId - Session ID that identifies which session to connect to.
   * @returns A reference to the actor session.
   *
   * @example
   * ```typescript
   * const session = base44.actors.Chat("lobby-1");
   * const conn = session.connect();
   * ```
   */
  (instanceId: string): ActorRef<N>;
}

/**
 * Provides access to actors and their shared, live sessions.
 *
 * Select an actor by name and session ID, then connect a client to the
 * session. Clients in the same session can exchange realtime messages through the
 * actor. The client works in the browser and in Node.
 *
 * ## Connection flow
 *
 * - Connect to a session with `base44.actors.<ActorName>(sessionId).connect()`.
 * - Subscribe to outgoing messages with {@link Connection.subscribe}.
 * - Send incoming messages with {@link Connection.send}.
 * - Close the connection with {@link Connection.close}.
 *
 * See [Actors Overview](/developers/backend/resources/actors/overview)
 * for actor concepts and terminology, and the [Actor Class Reference](/developers/backend/resources/actors/reference)
 * for the backend class API.
 *
 * ## Authentication modes
 *
 * This module is available in anonymous or user authentication mode
 * (`base44.actors`). It isn't available with service role authentication. Apps that
 * require login can reject anonymous connections in the actor's `handleConnect()` method.
 *
 * @example
 * ```typescript
 * const conn = base44.actors.Chat("session-1").connect({ id: "tab-1" });
 * const sub = conn.subscribe((msg) => console.log(msg));
 * conn.send({ type: "message", text: "hi" });
 * sub.unsubscribe();
 * conn.close();
 * ```
 */
export type ActorsModule = {
  [K in AllActorNames]: K extends keyof ActorRegistry
    ? ActorClient<string & K>
    : ActorClient;
} & Record<string, ActorClient>;
