/**
 * Maps actor names to their incoming and outgoing message types.
 *
 * Extend this interface through module augmentation when you want typed actor
 * messages without generating types with the CLI. For each actor, `toServer`
 * defines incoming messages that a client sends to the actor. `toClient` defines
 * outgoing messages that the actor sends to connected clients.
 *
 * To generate types from deployed actors instead, use the
 * [`types generate`](/developers/references/cli/commands/types-generate) CLI command.
 * To learn how incoming and outgoing messages work, see
 * [message types](/developers/backend/resources/actors/overview#message-types).
 *
 * @example
 * ```typescript
 * // Type messages for an actor
 * declare module "@base44/sdk" {
 *   interface ActorRegistry {
 *     chatRoom: {
 *       toClient: { type: "joined" | "left" | "message"; userId?: string; from?: string; text?: string };
 *       toServer: { type: "message"; text: string };
 *     };
 *   }
 * }
 * ```
 */
export interface ActorRegistry {}

/**
 * Lists actor names when your project includes types generated by the CLI
 * with [`types generate`](/developers/references/cli/commands/types-generate).
 *
 * The generated names provide autocomplete for deployed actors. To define
 * incoming and outgoing message types manually, augment [ActorRegistry](#actorregistry).
 */
export interface ActorNameRegistry {}

type AllActorNames = keyof ActorRegistry | keyof ActorNameRegistry;

type ToClientFor<N extends string> = N extends keyof ActorRegistry
  ? ActorRegistry[N] extends { toClient: infer I }
    ? I
    : unknown
  : unknown;

type ToServerFor<N extends string> = N extends keyof ActorRegistry
  ? ActorRegistry[N] extends { toServer: infer O }
    ? O
    : unknown
  : unknown;

/**
 * Configures the connection that [ActorRef.connect](#connect) opens.
 */
export interface ActorConnectOptions {
  /**
   * Connection ID that the actor receives as `conn.id`.
   *
   * To let the actor recognize the same client if it reconnects, use a stable
   * value, such as an ID stored per browser tab. If you omit this property, the
   * SDK generates a connection ID.
   *
   * For more about connection IDs, see
   * [connections](/developers/backend/resources/actors/reference#connections).
   */
  id?: string;
}

/**
 * Represents a listener for messages from the actor, registered with
 * [Connection.subscribe](#subscribe).
 */
export interface ActorSubscription {
  /**
   * Removes this listener. Other listeners and the socket stay open.
   *
   * @example
   * ```typescript
   * // Remove a listener
   * sub.unsubscribe();
   * ```
   */
  unsubscribe(): void;
}

/**
 * Represents a client's WebSocket connection to an actor session.
 *
 * [ActorRef.connect](#connect) returns this object. The socket buffers messages
 * you send before it opens.
 */
export interface Connection<N extends string = string> {
  /** Connection ID that the actor receives as `conn.id`. */
  readonly id: string;

  /**
   * Registers a listener for messages from the actor.
   *
   * You can register multiple listeners on the same connection.
   *
   * @param callback - Callback that runs for each message the actor sends to this connection.
   * @returns A subscription handle. Call `unsubscribe()` on it to remove this listener without closing the socket.
   *
   * @example
   * ```typescript
   * // Listen for messages from the actor
   * const sub = conn.subscribe((msg) => {
   *   console.log(msg);
   * });
   *
   * // Stop listening without closing the socket.
   * sub.unsubscribe();
   * ```
   */
  subscribe(callback: (data: ToClientFor<N>) => void): ActorSubscription;

  /**
   * Sends a message to the actor.
   *
   * The socket buffers messages until it opens. After you call [close](#close),
   * the socket drops further sends.
   *
   * @param data - Message to send to the actor. The type comes from [ActorRegistry](#actorregistry) when you register the actor there.
   *
   * @example
   * ```typescript
   * // Send a message to the actor
   * conn.send({ type: "message", text: "Hello" });
   * ```
   */
  send(data: ToServerFor<N>): void;

  /**
   * Closes the connection and removes all listeners.
   *
   * You can call this method more than once. A connection also closes itself
   * when it fails permanently. To open a new connection, call
   * [ActorRef.connect](#connect) again.
   *
   * @example
   * ```typescript
   * // Close the connection
   * conn.close();
   * ```
   */
  close(): void;
}

/**
 * Represents a reference to an actor session, identified by actor name and session ID.
 *
 * Call [connect](#connect) to open the WebSocket and get a [Connection](#connection).
 */
export interface ActorRef<N extends string = string> {
  /**
   * Creates or returns the [Connection](#connection) for this session.
   *
   * Repeated calls return the same connection until it closes. If the connection
   * fails permanently, for example because the actor doesn't exist or the actor
   * denies the connection, fix the cause and call `connect()` again. Then
   * subscribe again on the new connection.
   *
   * For a sample flow, see
   * [connect a client to a session](/developers/backend/resources/actors/sample-flows#connect-a-client-to-a-session).
   *
   * @param options - Optional connection settings, such as a stable connection ID.
   * @returns The [Connection](#connection) for this actor session.
   *
   * @example
   * ```typescript
   * // Connect to a session
   * const conn = base44.actors.chatRoom("session-1").connect({ id: "tab-1" });
   * ```
   */
  connect(options?: ActorConnectOptions): Connection<N>;
}

/**
 * Selects a session for a named actor.
 *
 * TypeScript infers message types when you register the actor in
 * [ActorRegistry](#actorregistry). [ActorNameRegistry](#actornameregistry)
 * provides autocomplete for actor names only.
 */
export interface ActorClient<N extends string = string> {
  /**
   * Gets a reference to an actor session.
   *
   * Clients that specify the same actor name and session ID join the same session.
   *
   * @param instanceId - Session ID that identifies which session to connect to.
   * @returns A reference to the actor session.
   *
   * @example
   * ```typescript
   * // Select a session
   * const session = base44.actors.chatRoom("session-1");
   * ```
   */
  (instanceId: string): ActorRef<N>;
}

/**
 * Actors module for connecting your app to actors. An actor is a backend process that you define
 * in your project and that multiple clients connect to at the same time. Each client joins a
 * session, identified by the actor name and a session ID, and clients in the same session share
 * its state.
 *
 * This module is the client side of an actor. Use it to join a session, send messages to the
 * actor, and receive the messages it sends back in realtime.
 *
 * To learn how actors work, see the [actors overview](/developers/backend/resources/actors/overview).
 * For a sample flow, see
 * [connect a client to a session](/developers/backend/resources/actors/sample-flows#connect-a-client-to-a-session).
 *
 * ## Authentication modes
 *
 * This module is available in anonymous and user authentication modes.
 * Apps that require login can reject anonymous connections in the actor's `handleConnect()` method.
 * To learn more, see [manage client connections](/developers/backend/resources/actors/sample-flows#manage-client-connections).
 *
 * @example
 * ```typescript
 * // Connect, subscribe, send, and close
 * const conn = base44.actors.chatRoom("session-1").connect({ id: "tab-1" });
 * const sub = conn.subscribe((msg) => console.log(msg));
 * conn.send({ type: "message", text: "hi" });
 * sub.unsubscribe();
 * conn.close();
 * ```
 */
export type ActorsModule = {
  [K in AllActorNames]: K extends keyof ActorRegistry
    ? ActorClient<string & K>
    : ActorClient;
} & Record<string, ActorClient>;
